export { default as auth } from './auth/index'
export { default as device } from './device/index'
export { default as register } from './register/index'
export { default as admin } from './admin/index'
export { default as db } from './db/index'
export { default as user } from './user/index'
export { default as manageDevice } from './manage-device/index'
