version: "3"

services:
  traefik:
    image: traefik:v1.7.18
    restart: always
    ports:
      - 80:80
      - 443:443
      - ${TRAEFIK_PANEL_PORT}:8080
    networks:
      - web-production
      - web-staging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
    environment:
      CF_API_EMAIL: ""
      CF_API_KEY: ""
    container_name: traefik 
            
networks:
  web-production:
    external: true
  web-staging:
    external: true

